### ISSUE TITLE
5.3.28 tag problem (same than 5.3.21)

### ISSUE THREAD

**Issue by Neustradamus** [berkeleydb/libdb#2]
@gburd: There is a tag problem for 5.3.28:
- https://github.com/berkeleydb/libdb/releases

Can you add the last code in master and create the good tag?

Thanks in advance.

**Comment by gburd** [comment]
Thank you for the comment but I don't quite understand the issue.  What is the "tag problem"?  What constitutes a "good tag"?

**Comment by Neustradamus** [comment]
@gburd: Currently :
- https://github.com/berkeleydb/libdb/releases/tag/v5.3.28 = https://github.com/berkeleydb/libdb/releases/tag/v5.3.21

Can you add the 5.3.28 code?
