### ISSUE TITLE
Berkeley DB JE (Java Edition) is missing

### ISSUE THREAD

**Issue by Neustradamus** [berkeleydb/libdb#4]
@gburd: Berkeley DB JE (Java Edition) is missing.

Can you add the source code?

Thanks in advance.

**Comment by Neustradamus** [comment]
@gburd: Notes:
- 2.0 - 6.0.19 is licensed under the Sleepycat License
- 6.0.20 - 7.3.6 is licensed under the GNU AGPL v3
- 7.3.7 and newer is licensed under the Apache License, Version 2.0

**Comment by gburd** [comment]
https://github.com/berkeleydb/je

**Comment by Neustradamus** [comment]
@gburd: Thanks.
