### ISSUE TITLE
6.0.20 and newer is licensed under the GNU AGPL v3

### ISSUE THREAD

**Issue by Neustradamus** [berkeleydb/libdb#5]
@gburd: The source code after can be published after 6.0.19 too:
- 2.0 - 6.0.19 is licensed under the Sleepycat License
- 6.0.20 and newer is licensed under the GNU AGPL v3

**Comment by gburd** [comment]
Yes, exactly.  This repo will not replicate GPL or AGPL licensed works.

**Comment by Neustradamus** [comment]
@gburd: I have commented here:
- https://github.com/berkeleydb/libdb/issues/7
